### ISSUE TITLE
Change Redundant colors on legend

### ISSUE THREAD

**Issue by ssfinch** [nasa-nccs-hpda/modis-water-classification#4]
There are 3 redundant colors on the legend that are the same as 3 of the Seven Class: 

"QA - High Slope Surface" (dark pink),
"Difference C6 ONLY Water" (red),
"C6 - Water" (royal blue). 

Change colors for these 3 so it's not confused with Seven Class colors if all layers are selected.

![Screenshot 2023-01-17 at 4 42 13 PM](https://user-images.githubusercontent.com/69205623/213019300-792e377f-b3a1-4efc-8754-35302d8e3253.png)

**Comment by cssprad1** [comment]
Fixed in PR #7
